services:
  - type: web
    name: function1
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python -m spacy download en_core_web_sm
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHONPATH
        value: /opt/render/project/src
    healthCheckPath: /health

---